apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.common.name }}-grafana
  labels:
    {{- include "news-feed.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
    - port: {{ .Values.grafana.service.port }}
      targetPort: web
      protocol: TCP
      name: web
  selector:
    app.kubernetes.io/component: grafana