{{- if .Values.kafka.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.common.name }}-kafka
  labels:
    {{- include "news-feed.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
spec:
  type: {{ .Values.kafka.service.type }}
  ports:
    - port: {{ .Values.kafka.service.port }}
      targetPort: {{ .Values.kafka.service.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Values.common.name }}
    app.kubernetes.io/component: kafka
{{- end }}
