{{- if and .Values.kafka.enabled .Values.kafka.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.common.name }}-kafka-pvc
  labels:
    {{- include "news-feed.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.kafka.persistence.size }}
  {{- if .Values.kafka.persistence.storageClass }}
  storageClassName: {{ .Values.kafka.persistence.storageClass }}
  {{- end }}
{{- end }}
