{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.common.name }}-redis
  labels:
    {{- include "news-feed.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Values.common.name }}
    app.kubernetes.io/component: redis
{{- end }}
