{{- if and .Values.timescaledb.enabled .Values.timescaledb.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.common.name }}-timescaledb-pvc
  labels:
    {{- include "news-feed.labels" . | nindent 4 }}
    app.kubernetes.io/component: timescaledb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.timescaledb.persistence.size }}
  {{- if .Values.timescaledb.persistence.storageClass }}
  storageClassName: {{ .Values.timescaledb.persistence.storageClass }}
  {{- end }}
{{- end }}
